# Generated by Django 5.0.6 on 2026-09-03 04:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('synopsis', models.TextField(blank=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='seasons/posters/%Y/')),
                ('air_date', models.DateField(default=django.utils.timezone.now)),
                ('trailer_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['season_number'],
            },
        ),
    ]
