# Generated by Django 5.0.6 on 2026-09-03 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='series.series'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('series', 'season_number')},
        ),
    ]
