# Generated by Django 5.0.6 on 2026-09-03 04:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('synopsis', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('air_date', models.DateField(default=django.utils.timezone.now)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='episodes/thumbnails/%Y/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='episodes/videos/%Y/')),
                ('stream_url', models.URLField(blank=True, max_length=500)),
                ('intro_start_sec', models.PositiveIntegerField(default=60, help_text='Timestamp where opening theme begins')),
                ('intro_end_sec', models.PositiveIntegerField(default=150, help_text='Timestamp where opening theme ends')),
                ('outro_start_sec', models.PositiveIntegerField(default=2550, help_text='Timestamp where end credits begin')),
                ('is_free_preview', models.BooleanField(default=False)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['season__season_number', 'episode_number'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('language_name', models.CharField(default='English', max_length=50)),
                ('vtt_file', models.FileField(blank=True, null=True, upload_to='episodes/subtitles/%Y/')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
