# Generated by Django 5.0.6 on 2026-09-03 04:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.UUIDField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='StreamingToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.UUIDField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('is_consumed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
