# Generated by Django 5.0.6 on 2026-09-03 04:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodes', '0002_initial'),
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_position_seconds', models.PositiveIntegerField(default=0)),
                ('total_duration_seconds', models.PositiveIntegerField(default=1)),
                ('percentage_watched', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('device_type', models.CharField(default='Desktop', max_length=50)),
                ('last_watched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='episodes.episode')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_watched_at'],
                'indexes': [models.Index(fields=['user', '-last_watched_at'], name='history_wat_user_id_ff46b9_idx'), models.Index(fields=['user', 'is_completed'], name='history_wat_user_id_28b92d_idx')],
            },
        ),
    ]
