# Generated by Django 5.0.6 on 2026-09-03 04:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('USER_LOGIN', 'User Sign In'), ('USER_REGISTER', 'User Registration'), ('SUBSCRIPTION_UPGRADE', 'Subscription Upgraded'), ('PASSWORD_RESET', 'Password Reset Initiated'), ('CONTENT_PUBLISHED', 'Content Published'), ('REPORT_RESOLVED', 'Moderation Report Resolved')], default='USER_LOGIN', max_length=50)),
                ('details', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
