# Generated by Django 5.0.6 on 2026-09-03 04:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_redemptions', models.PositiveIntegerField(default=1000)),
                ('times_redeemed', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier_code', models.CharField(choices=[('FREE', 'Free Ad-Supported'), ('BASIC', 'Basic HD (720p)'), ('STANDARD', 'Standard Full HD (1080p)'), ('VIP_4K', 'VIP Ultra 4K HDR & Dolby Atmos')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('max_screens', models.PositiveSmallIntegerField(default=1)),
                ('max_resolution', models.CharField(default='1080p', max_length=20)),
                ('has_dolby_atmos', models.BooleanField(default=False)),
                ('allows_offline_downloads', models.BooleanField(default=False)),
                ('ad_free', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('badge_label', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=15)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
