# Generated by Django 5.0.6 on 2026-09-03 04:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('synopsis', models.TextField()),
                ('first_air_date', models.DateField(default=django.utils.timezone.now)),
                ('last_air_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing Series'), ('CONCLUDED', 'Concluded'), ('UPCOMING', 'Upcoming Premiere'), ('HIATUS', 'On Hiatus')], default='ONGOING', max_length=20)),
                ('content_rating', models.CharField(choices=[('TV-Y', 'TV-Y (All Children)'), ('TV-PG', 'TV-PG (Parental Guidance)'), ('TV-14', 'TV-14 (Parents Strongly Cautioned)'), ('TV-MA', 'TV-MA (Mature Audiences Only)')], default='TV-MA', max_length=10)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='series/posters/%Y/')),
                ('backdrop_image', models.ImageField(blank=True, null=True, upload_to='series/backdrops/%Y/')),
                ('trailer_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_original', models.BooleanField(default=True, help_text='CineVerse Original Series')),
                ('is_vip_only', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=1, default=9.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creators', models.ManyToManyField(blank=True, related_name='created_series', to='people.person')),
                ('genres', models.ManyToManyField(blank=True, related_name='series', to='genres.genre')),
                ('tags', models.ManyToManyField(blank=True, related_name='series', to='genres.tag')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['-first_air_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SeriesCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=150)),
                ('billing_order', models.PositiveSmallIntegerField(default=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_roles', to='people.person')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_cast', to='series.series')),
            ],
            options={
                'ordering': ['billing_order'],
                'unique_together': {('series', 'person', 'character_name')},
            },
        ),
        migrations.AddField(
            model_name='series',
            name='cast_members',
            field=models.ManyToManyField(blank=True, related_name='acted_series', through='series.SeriesCast', to='people.person'),
        ),
    ]
