# Generated by Django 5.0.6 on 2026-09-03 04:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('synopsis', models.TextField()),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveIntegerField(default=120, help_text='Runtime in minutes')),
                ('content_rating', models.CharField(choices=[('G', 'G (General Audiences)'), ('PG', 'PG (Parental Guidance Suggested)'), ('PG-13', 'PG-13 (Parents Strongly Cautioned)'), ('R', 'R (Restricted 17+)'), ('NC-17', 'NC-17 (Adults Only)'), ('NR', 'Not Rated')], default='PG-13', max_length=10)),
                ('resolution', models.CharField(choices=[('4K', '4K Ultra HD (2160p HDR)'), ('1080P', 'Full HD (1080p)'), ('720P', 'HD (720p)'), ('480P', 'SD (480p)')], default='4K', max_length=10)),
                ('audio_format', models.CharField(default='Dolby Atmos 5.1', max_length=50)),
                ('aspect_ratio', models.CharField(default='2.39:1 Anamorphic', max_length=20)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='movies/posters/%Y/')),
                ('backdrop_image', models.ImageField(blank=True, null=True, upload_to='movies/backdrops/%Y/')),
                ('trailer_url', models.URLField(blank=True, help_text='YouTube or HLS trailer URL', max_length=500)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='movies/videos/%Y/')),
                ('stream_url', models.URLField(blank=True, help_text='CDN or HLS Stream manifest (.m3u8 / .mp4)', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_original', models.BooleanField(default=False, help_text='CineVerse Original Production')),
                ('is_vip_only', models.BooleanField(default=False, help_text='Restricted to 4K VIP subscribers')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=1, default=8.5, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directors', models.ManyToManyField(blank=True, related_name='directed_movies', to='people.person')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='genres.genre')),
                ('tags', models.ManyToManyField(blank=True, related_name='movies', to='genres.tag')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=150)),
                ('billing_order', models.PositiveSmallIntegerField(default=1)),
                ('is_lead', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cast', to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_roles', to='people.person')),
            ],
            options={
                'ordering': ['billing_order'],
                'unique_together': {('movie', 'person', 'character_name')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast_members',
            field=models.ManyToManyField(blank=True, related_name='acted_movies', through='movies.MovieCast', to='people.person'),
        ),
        migrations.CreateModel(
            name='MovieQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_label', models.CharField(max_length=20)),
                ('bitrate_kbps', models.PositiveIntegerField(default=5000)),
                ('video_stream_url', models.URLField(max_length=500)),
                ('file_size_mb', models.FloatField(default=1500.0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_variants', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('language_name', models.CharField(default='English', max_length=50)),
                ('vtt_file', models.FileField(blank=True, null=True, upload_to='movies/subtitles/%Y/')),
                ('is_default', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movies.movie')),
            ],
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug'], name='movies_movi_slug_5ef9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_published', 'is_featured'], name='movies_movi_is_publ_b6f216_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-view_count'], name='movies_movi_view_co_3e7735_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moviesubtitle',
            unique_together={('movie', 'language_code')},
        ),
    ]
