# Generated by Django 5.0.6 on 2026-09-03 04:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('PAYMENT_SUCCESS', 'Payment Received'), ('SUBSCRIPTION_RENEWAL', 'Subscription Renewal'), ('NEW_RELEASE', 'New Movie or Episode Available'), ('RECOMMENDATION', 'Recommended For You'), ('SECURITY_ALERT', 'Security Alert')], default='PAYMENT_SUCCESS', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_url', models.CharField(default='/', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
